server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/hospital_optimization_db

# JWT Configuration
app.jwt.secret=SmartHospitalManagerSecretKeyMustBeVeryLongAndSecureForHS512AlgorithmSecurity2026!
app.jwt.expiration-ms=86400000

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.hospital.optimization=DEBUG
